[package]
name = "elaine-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "eln"
path = "src/main.rs"


[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
colored = "2.1"
regex = "1.10"

